// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Speakers.Infrastructure.Data;


#nullable disable

namespace Speakers.API.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    partial class SpeakerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Speakers.Domain.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Ürkmez",
                            Name = "Türkay"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Ağıt",
                            Name = "Burak"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Günebakan",
                            Name = "Melinda"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "Sümbül",
                            Name = "Melahat"
                        },
                        new
                        {
                            Id = 5,
                            LastName = "Candan",
                            Name = "Melike"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
